# Generated by Django 5.0.2 on 2025-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('subscription_type', models.CharField(choices=[('investors', 'Investors'), ('resources', 'Resources')], default='resources', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email', 'subscription_type'], name='contact_app_email_9797e1_idx'), models.Index(fields=['is_active', 'subscription_type'], name='contact_app_is_acti_5f36be_idx')],
            },
        ),
    ]
