# Generated by Django 4.2.23 on 2025-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
